services:
  db:
    image: postgres:16.3-alpine
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    env_file:
      - .env.production
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile-production
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    volumes:
      - assets_volume:/app/public

  nginx:
    image: itcrowdarg/nginx-docker-proxy
    env_file:
      - .env.production
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - assets_volume:/app/public

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-production
    command: bundle exec sidekiq -e production -q normal
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:
  assets_volume:
