services:
  db:
    image: postgres:16.3-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    volumes:
      - redis_data:/data

  app:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -e development -q normal
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/

volumes:
  db_data:
  redis_data:
  bundler_gems:
